### ISSUE TITLE
MAC Error when SftpClient.DownloadFile(UWP)

### ISSUE THREAD

**Issue by Wufus** [sshnet/SSH.NET#1017]
**Remote Server Information**
Remote SSH Server version: SSH-2.0-OpenSSH_7.9
Remote Operating System distribution name and architecture: Linux aarch64
What kind of access do you have?: Full physical and software access
Does Putty/WinSCP work?: yes

**Local Machine Information**
Operating System: Windows 10 21H2
.NET SDKs versions installed: 2.1.511, 2.1.801, 5.0.400

**Project information**
What is your target framework and architecture?: x64 UWP
Is your project multi-threaded/complex?:

**Source Code**
Sample Code:
```
Sample Code:
var sftp = new SftpClient(MyIp, MyLogin, MyPassword);
sftp.Connect();
var memStream= new MemoryStream();
sftp.DownloadFile($"/opt/myfile.json", memStream);
```
Exceptions and Stack Trace/Call Stack:
```
Renci.SshNet.Common.SshConnectionException: MAC error
   at Renci.SshNet.SubsystemSession.WaitOnHandle(WaitHandle waitHandle, Int32 millisecondsTimeout)
   at Renci.SshNet.Sftp.SftpSession.RequestRealPath(String path, Boolean nullOnError)
   at Renci.SshNet.Sftp.SftpSession.GetCanonicalPath(String path)
   at Renci.SshNet.SftpClient.InternalDownloadFile(String path, Stream output, SftpDownloadAsyncResult asyncResult, Action`1 downloadCallback)
   at Renci.SshNet.SftpClient.DownloadFile(String path, Stream output, Action`1 downloadCallback)
   at RouteLoader2022.Loader.Network.FtpRouteAnalyzer.<>c__DisplayClass0_0.<AnalyzeAsync>b__0() in E:\Repos\RouteLoader2022\RouteLoader2022\Loader\Network\FtpRouteAnalyzer.cs:line 42
```

**File transfer related**
Transfer over LAN or Internet?: LAN
File size in bytes: 29876 Bytes
Uploading or Downloading? Downloading
Does remote server have enough space to store the file? Yes
Do you have access to the file being uploaded or downloaded? Yes

Increasingsize of `SftpClient.BufferSize` doesn't help
When do `var readStream = SftpClient.OpenRead` and then `readStream.Read/ReadByte/ReadAsync` same MAC Error exceptions throws

**Comment by Wufus** [comment]
I clone this repo for debugging and see more definite error.
```
   в Renci.SshNet.Sftp.SftpFileReader.Read() in E:\Repos\SSH.NET\src\Renci.SshNet\Sftp\SftpFileReader.cs:94
   в Renci.SshNet.SftpClient.InternalDownloadFile(String path, Stream output, SftpDownloadAsyncResult asyncResult, Action`1 downloadCallback) in E:\Repos\SSH.NET\src\Renci.SshNet\SftpClient.cs:2063
   в Renci.SshNet.SftpClient.DownloadFile(String path, Stream output, Action`1 downloadCallback) in E:\Repos\SSH.NET\src\Renci.SshNet\SftpClient.cs:640
```
I see that `Renci.SshNet.Sftp.SftpFileReader.Read():87` has `_queue` that always empty. And very soon `_exception` sets at `MAC error`.
But if i start debugging line by line after `Renci.SshNet.SftpClient.InternalDownloadFile:2063`, and problems do not appear.
Because `Renci.SshNet.Sftp.SftpFileReader.ReadCompletedCore():394` add data elements in `_queue`. So i can download files more than 30KB.
The error `MAC error` comes from `Renci.SshNet.Sftp.SftpFileReader.ContinueReadAhead():353` with Exception ex.StacTrace
```
   в Renci.SshNet.SubsystemSession.WaitAny(WaitHandle[] waitHandles, Int32 millisecondsTimeout) in E:\Repos\SSH.NET\src\Renci.SshNet\SubsystemSession.cs:374
   в Renci.SshNet.Sftp.SftpFileReader.ContinueReadAhead() in E:\Repos\SSH.NET\src\Renci.SshNet\Sftp\SftpFileReader.cs:340
```
More deeply `MAC error` is the consequence of "TCP ZeroWindow".
I attach [wireshark log](https://github.com/sshnet/SSH.NET/files/11650395/wireshark.zip) of SHH.NET where you can see "TCP ZeroWindow".
And attach [winreshark log of WinSCP by SFTP](https://github.com/sshnet/SSH.NET/files/11650430/WinSCP.by.SFTP.zip) where no any problems.
So it looks like SSH.NET problem
