### ISSUE TITLE
Ignore server certificate with classic password authentication

### ISSUE THREAD

**Issue by LaurensVanAcker** [sshnet/SSH.NET#1064]
How can we ignore the server certificate?
The server is maintained by a third party and contains an untrusted certificate.
When using a classic username and password authentication, we get this, probably because the certificate isn't accepted:

```
[2022-12-16T11:38:21.693Z] Executed 'Functions.Download' (Failed, Id=599a0315-bd0b-4e82-b634-96240b284b12, Duration=5253ms)
[2022-12-16T11:38:21.694Z] System.Private.CoreLib: Exception while executing function: Functions.Download. System.Private.CoreLib: Result: Failure
Exception: System.AggregateException: One or more errors occurred. ()
[2022-12-16T11:38:21.696Z]  ---> Renci.SshNet.Common.SshException
[2022-12-16T11:38:21.702Z]    at Renci.SshNet.Sftp.SftpSession.RequestOpen(String path, Flags flags, Boolean nullOnError)
[2022-12-16T11:38:21.706Z]    at Renci.SshNet.SftpClient.InternalUploadFile(Stream input, String path, Flags flags, SftpUploadAsyncResult asyncResult, Action`1 uploadCallback)
[2022-12-16T11:38:21.708Z]    at Renci.SshNet.SftpClient.UploadFile(Stream input, String path, Boolean canOverride, Action`1 uploadCallback)
```

**Comment by WojciechNagorski** [comment]
I'm closing the issue, the report does not contain enough information to reproduce the bug.
