### ISSUE TITLE
Ubuntu 22.04 Key exchange negotiation failed

### ISSUE THREAD

**Issue by okarpov** [sshnet/SSH.NET#1067]
Renci.SshNet.Common.SshConnectionException: Key exchange negotiation failed.
   at Renci.SshNet.Session.WaitOnHandle(WaitHandle waitHandle, TimeSpan timeout) in SSH.NET-rsa-sha2-256\src\Renci.SshNet\Session.cs:line 977
   at Renci.SshNet.Session.Connect() in SSH.NET-rsa-sha2-256\src\Renci.SshNet\Session.cs:line 628
   at Renci.SshNet.BaseClient.CreateAndConnectSession() in SSH.NET-rsa-sha2-256\src\Renci.SshNet\BaseClient.cs:line 526
   at Renci.SshNet.BaseClient.Connect() in SSH.NET-rsa-sha2-256\src\Renci.SshNet\BaseClient.cs:line 228

**Comment by WojciechNagorski** [comment]
I'm closing the issue, the report does not contain enough information to reproduce the bug.
