### ISSUE TITLE
ARM64 - Permission denied

### ISSUE THREAD

**Issue by vasanthtt** [sshnet/SSH.NET#1068]
I deployed a working solution in the ARM64 container and got Permission denied. From the same container, I tried connecting using ssh client on the same setting and succeeded.

**host config**
```
{
  "runtimeVersion": ".NET 7.0.1",
  "osVersion": "Linux 5.15.0-1025-oracle #31-Ubuntu SMP Fri Nov 25 17:03:15 UTC 2022",
  "osArchitecture": "Arm64"
  "user": "root",
}
```
**Error**
```
TargetSite = Void Authenticate(Renci.SshNet.IConnectionInfoInternal, Renci.SshNet.ISession)
Message = Permission denied (publickey).
Data = System.Collections.ListDictionaryInternal
InnerException = 
HelpLink = 
Source = Renci.SshNet
HResult = -2146233088
StackTrace =    at Renci.SshNet.ClientAuthentication.Authenticate(IConnectionInfoInternal connectionInfo, ISession session)
   at Renci.SshNet.ConnectionInfo.Authenticate(ISession session, IServiceFactory serviceFactory)
   at Renci.SshNet.Session.Connect()
   at Renci.SshNet.BaseClient.CreateAndConnectSession()
   at Renci.SshNet.BaseClient.Connect()
```

**Comment by vasanthtt** [comment]
I am not sure if this issue is related to ssh.net. It is not only authenticating via the internet or my cloud Linux VM instance (ARM)

**Comment by vasanthtt** [comment]
Log here
```
Jan 17 09:39:48 in-cloud sshd[1892867]: debug2: input_userauth_request: try method publickey [preauth]
Jan 17 09:39:48 in-cloud sshd[1892867]: debug2: userauth_pubkey: valid user ubuntu attempting public key ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCTm4PHvPgrtZxGajQFDTToyU66JsriCrur41Sq5/mgFX3HSKkiTfV/teSn6WAGh6fB5ZF+2WsOmbTm+LBbt/9W4viTgKZ2gvPkzEuhzVohxWmLtiCCviMvtZfYNw7Dkap9006FlHCAyjzWI+HWjUaMAAa/+D02YRO9SljgG+Ni8s01+R5nidBF6RdmVTw8+kZSFmhfTrux8D6+taOtys4yzkiKGoVCRH9nm/sFNWBdm4nkVD2XkpA8RS7J2STP5VdRWh1Q4heVevJtcMF3WhvNoMCsYrdddfVy+KsmZxu51zXP9MDbug2eOx3wH8/2gM+3jpMlPcoLypOuxIiBZxap5WDH64vQ3NnRbMrhxhpHufut3CtB/4Wm8LJkRtAj7PIJ3+UNnx9ylwF
Jan 17 09:39:48 in-cloud sshd[1892867]: userauth_pubkey: key type ssh-rsa not in PubkeyAcceptedAlgorithms [preauth]
Jan 17 09:39:48 in-cloud sshd[1892867]: debug2: userauth_pubkey: authenticated 0 pkalg ssh-rsa [preauth]
Jan 17 09:39:48 in-cloud sshd[1892867]: debug3: user_specific_delay: user specific delay 0.000ms [preauth]
Jan 17 09:39:48 in-cloud sshd[1892867]: debug3: ensure_minimum_time_since: elapsed 0.077ms, delaying 5.028ms (requested 5.105ms) [preauth]
Jan 17 09:39:48 in-cloud sshd[1892867]: debug3: userauth_finish: failure partial=0 next methods="publickey" [preauth]
Jan 17 09:39:48 in-cloud sshd[1892867]: debug3: send packet: type 51 [preauth]
Jan 17 09:39:48 in-cloud sshd[1892867]: Connection closed by authenticating user ubuntu 49.204.117.34 port 18402 [preauth]
Jan 17 09:39:48 in-cloud sshd[1892867]: debug1: do_cleanup [preauth]
Jan 17 09:39:48 in-cloud sshd[1892867]: debug3: PAM: sshpam_thread_cleanup entering [preauth]
Jan 17 09:39:48 in-cloud sshd[1892867]: debug1: monitor_read_log: child log fd closed
Jan 17 09:39:48 in-cloud sshd[1892867]: debug3: mm_request_receive: entering
Jan 17 09:39:48 in-cloud sshd[1892867]: debug1: do_cleanup
Jan 17 09:39:48 in-cloud sshd[1892867]: debug1: PAM: cleanup
Jan 17 09:39:48 in-cloud sshd[1892867]: debug3: PAM: sshpam_thread_cleanup entering
Jan 17 09:39:48 in-cloud sshd[1892867]: debug1: Killing privsep child 1892868
Jan 17 09:39:48 in-cloud sshd[1892867]: debug1: audit_event: unhandled event 12
```

**Comment by vasanthtt** [comment]
`ssh-keygen -m PEM -t rsa -b 4096`

I generated new keys with above cmd and move pub to host. I can login via terminal but still not from code. I still get 
`userauth_pubkey: key type ssh-rsa not in PubkeyAcceptedAlgorithms [preauth]`

**Comment by vasanthtt** [comment]
this fixed

Add this line in /etc/ssh/sshd_config.
`PubkeyAcceptedAlgorithms=+ssh-rsa`

And then restart sshd service.
`$ sudo systemctl restart sshd`
