### ISSUE TITLE
SSH.NET cannot work with SSH Server on Windows Server 2012

### ISSUE THREAD

**Issue by 1443403216** [sshnet/SSH.NET#1076]
SSH.NET with Windows SSH Server on Windows Server 2012 above (Example: Windows Server 2016) works smoothly, but no luck with Windows Server 2012. 

BTW, It works ok by using putty or other ssh clients.

See errors below, please advise. Thanks!

Code:
`
 using (SshClient sshClient = new SshClient(dbServer.Host, dbServer.User, dbServer.Password))
{
	sshClient.HostKeyReceived += (sender, e) =>
	{
		e.CanTrust = true;
	};
	sshClient.Connect();
} 
`

Error:
`2023-01-30 13:48:10.090 +00:00 [Error] Job DEFAULT.BackupJob threw an unhandled Exception: 
Renci.SshNet.Common.SshConnectionException: Connection reset by peer
 ---> System.Net.Sockets.SocketException (104): Connection reset by peer
   at Renci.SshNet.Abstractions.SocketAbstraction.Read(Socket socket, Byte[] buffer, Int32 offset, Int32 size, TimeSpan timeout)
   at Renci.SshNet.Session.TrySocketRead(Byte[] buffer, Int32 offset, Int32 length)
   at Renci.SshNet.Session.ReceiveMessage()
   at Renci.SshNet.Session.MessageListener()
   --- End of inner exception stack trace ---
   at Renci.SshNet.Session.WaitOnHandle(WaitHandle waitHandle, TimeSpan timeout)
   at Renci.SshNet.Session.WaitOnHandle(WaitHandle waitHandle)
   at Renci.SshNet.Session.Connect()
   at Renci.SshNet.BaseClient.CreateAndConnectSession()
   at Renci.SshNet.BaseClient.Connect()
   at BackupHelper.Jobs.BackupJob.Execute(IJobExecutionContext context) in /src/BackupHelper/Jobs/BackupJob.cs:line 52
   at Quartz.Simpl.MicrosoftDependencyInjectionJobFactory.ScopedJob.Execute(IJobExecutionContext context)
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)`

**Comment by 1443403216** [comment]
It works ok by using FreeSSHd on windows server 2012, see: http://www.freesshd.com/
