### ISSUE TITLE
Tectia SSH Server on z/OS mainframe

### ISSUE THREAD

**Issue by mmaguigan** [sshnet/SSH.NET#1243]
I have seen this mentioned before in the issues, but when connecting to a Tectia SSH server on an IBM mainframe, this error immediately occurs at connection:

`System.NotSupportedException: Data longer than 2147483647 is not supported.`

I would be happy to investigate patching the issue myself if some initial guidance could be provided.

EDIT:

Stacktrace is below
```
   at Renci.SshNet.Messages.Transport.IgnoreMessage.LoadData()
   at Renci.SshNet.Common.SshData.LoadInternal(Byte[] value, Int32 offset, Int32 count)
   at Renci.SshNet.Common.SshData.Load(Byte[] data, Int32 offset, Int32 count)
   at Renci.SshNet.Session.LoadMessage(Byte[] data, Int32 offset, Int32 count)
   at Renci.SshNet.Session.ReceiveMessage(Socket socket)
   at Renci.SshNet.Session.MessageListener()
--- End of stack trace from previous location ---
   at Renci.SshNet.Session.WaitOnHandle(WaitHandle waitHandle, TimeSpan timeout)
   at Renci.SshNet.Session.WaitOnHandle(WaitHandle waitHandle)
   at Renci.SshNet.Session.ConnectAsync(CancellationToken cancellationToken)
   at Renci.SshNet.BaseClient.CreateAndConnectSessionAsync(CancellationToken cancellationToken)
   at Renci.SshNet.BaseClient.ConnectAsync(CancellationToken cancellationToken)
   at UserQuery.Main(), line 17
```

**Comment by Rob-Hague** [comment]
Hi @mmaguigan, thanks for reporting. There was actually already a fix waiting to be merged, which we have done now. You can download the code in this repo and give it a try. Cheers

**Comment by mmaguigan** [comment]
@Rob-Hague, thanks so much that's terrific. I just tested it out and can confirm that it resolved the connection issue and I was able to list the contents of a directory :smile:

**Comment by Rob-Hague** [comment]
Glad to hear it 🙂

**Comment by WojciechNagorski** [comment]
The 2023.0.1 version has been released to Nuget: https://www.nuget.org/packages/SSH.NET/2023.0.1
