### ISSUE TITLE
Unstable integration test Test_Sftp_Multiple_Async_Upload_And_Download_10Files_5MB_Each

### ISSUE THREAD

**Issue by WojciechNagorski** [sshnet/SSH.NET#1253]
```
Failed Test_Sftp_Multiple_Async_Upload_And_Download_10Files_5MB_Each [9 s]
  Error Message:
   Assert.IsTrue failed. Uploaded and downloaded bytes does not match
  Stack Trace:
     at Renci.SshNet.IntegrationTests.OldIntegrationTests.SftpClientTest.Test_Sftp_Multiple_Async_Upload_And_Download_10Files_5MB_Each() in /home/appveyor/projects/ssh-net/test/Renci.SshNet.IntegrationTests/OldIntegrationTests/SftpClientTest.Upload.cs:line 233
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
  Standard Output Messages:
 SSH Server host name: 127.0.0.1
 SSH Server port: 32769
 5iovfbli.ykm
 UploadedBytes: 5242880
 DownloadedBytes: 5242880
 UploadedHash: 1b829b119bfeb98e8446755911d7d680
 DownloadedHash: 1b829b119bfeb98e8446755911d7d680
 glzjnmjw.iiq
 UploadedBytes: 5242880
 DownloadedBytes: 5242880
 UploadedHash: 8e0c19f0a0a8d291e9ced2a5e608e322
 DownloadedHash: 8e0c19f0a0a8d291e9ced2a5e608e322
 quhkvyug.zy3
 UploadedBytes: 5242880
 DownloadedBytes: 5242880
 UploadedHash: 4c70cfc9e8f4aa12f6a793042fdba776
 DownloadedHash: 4c70cfc9e8f4aa12f6a793042fdba776
 ypghiybv.4cm
 UploadedBytes: 5242880
 DownloadedBytes: 5242880
 UploadedHash: d3c949929[381](https://ci.appveyor.com/project/drieseng/ssh-net/build/job/laf9893flglsi6rg#L381)1b03588f857761f407f5
 DownloadedHash: d3c9499293811b03588f857761f407f5
 x4db0pr0.dhb
 UploadedBytes: 5242880
 DownloadedBytes: 5242880
 UploadedHash: e658a12e0ff01f0d035b4a994c82c491
 DownloadedHash: e658a12e0ff01f0d035b4a994c82c491
 fmwna44p.dxc
 UploadedBytes: 5242880
 DownloadedBytes: 5242880
 UploadedHash: 9e1344cc1f556b9eb91beda2e08d5f06
 DownloadedHash: 9e1344cc1f556b9eb91beda2e08d5f06
 iq13zo04.2xz
 UploadedBytes: 5242880
 DownloadedBytes: 5242880
 UploadedHash: 45cd97ebe2c943a38e9a4254ab984e44
 DownloadedHash: 45cd97ebe2c943a38e9a4254ab984e44
 e4rrcgsd.303
 UploadedBytes: 5242880
 DownloadedBytes: 5242880
 UploadedHash: f6f91ee74b9f359a698a8c7c1cbedce5
 DownloadedHash: f6f91ee74b9f359a698a8c7c1cbedce5
 kxnlrzbo.5cm
 UploadedBytes: 5242880
 DownloadedBytes: 5242880
 UploadedHash: 085db7b088cdc29444db63b26157317f
 DownloadedHash: 085db7b088cdc29444db63b26157317f
 2rwf4c0a.mq4
 UploadedBytes: 5242880
 DownloadedBytes:  5240800  <---- here is a problem
 UploadedHash: 196682a78dea5da9c6d6d79c0427ce20
 DownloadedHash: 196682a78dea5da9c6d6d79c0427ce20
```

**Comment by Rob-Hague** [comment]
Fixed by #1184

**Comment by scott-xu** [comment]
Can this issue be closed? @WojciechNagorski

**Comment by WojciechNagorski** [comment]
I think it can. if something fail we will open it.

**Comment by Rob-Hague** [comment]
It failed in https://ci.appveyor.com/project/drieseng/ssh-net/builds/48717790/job/ablpqnf51m4drswd/tests 🙁

**Comment by Rob-Hague** [comment]
Maybe it's related to #957

**Comment by Rob-Hague** [comment]
sshd says

```
debug sshd.pam[24]: debug2: channel 0: window 524288 sent adjust 32768
debug sshd.pam[24]: debug2: channel 0: window 557056 sent adjust 16384
err internal-sftp[25]: error: bad message from 172.17.0.1 local user sshnet   <--------
debug sshd.pam[24]: debug2: channel 0: read 0 from efd 10
debug sshd.pam[24]: debug2: channel 0: closing read-efd 10
debug sshd.pam[24]: debug1: Received SIGCHLD.
```

SSH.NET says

```
Channel#1 received request exit-status 11
```

It comes from https://github.com/openssh/openssh-portable/blob/49f325fd47af4e53fcd7aafdbcc280e53f5aa5ce/sftp-server.c#L1818-L1822

`SFTP_MAX_MSG_LENGTH` is 256 * 1024. As far as I can tell we comply with the server channel window and also do not exceed 32 * 1024 for an SFTP packet. It looks like sshd pipes the channel data to stdin of the sftp process - I don't see it combining packets or anything like that. Don't know how that SFTP_MAX_MSG_LENGTH check is failing.
