### ISSUE TITLE
System.InvalidOperationException

### ISSUE THREAD

**Issue by FrankCV2048** [sshnet/SSH.NET#1301]
the exception call stack:
System.InvalidOperationException
  HResult=0x80131509
  Message=在已经完成任务后，尝试将任务转换为最终状态。
  Source=mscorlib
  StackTrace:
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception)
   at Renci.SshNet.Abstractions.SocketExtensions.<ConnectAsync>d__1.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at Renci.SshNet.Abstractions.SocketExtensions.AwaitableSocketAsyncEventArgs.SetCompleted()
   at Renci.SshNet.Abstractions.SocketExtensions.AwaitableSocketAsyncEventArgs.<.ctor>b__3_0(Object sender, SocketAsyncEventArgs e)
   at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
   at System.Net.Sockets.SocketAsyncEventArgs.ExecutionCallback(Object ignored)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncFailure(SocketError socketError, Int32 bytesTransferred, SocketFlags flags)
   at System.Net.Sockets.SocketAsyncEventArgs.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)

**Comment by FrankCV2048** [comment]
[SSHNETAsyncTest.zip](https://github.com/sshnet/SSH.NET/files/14106188/SSHNETAsyncTest.zip)
