### ISSUE TITLE
Renci.SshNet makes application to crash after unhandled NullReferenceException exception

### ISSUE THREAD

**Issue by a-saqib** [sshnet/SSH.NET#134]
Application is crashing during uploading a file (1.5GB), leaving following call stack in Event Viewer. Retrying upload after few minutes corrects the problem. Any help will be greatly appreciated. 

Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
Stack:
   at Renci.SshNet.KeyboardInteractiveAuthenticationMethod+<>c__DisplayClass3.<Session_MessageReceived>b__0()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by a-saqib** [comment]
Here's some more info regarding my setup. I am uploading same files on 14+ hosts in parallel. Is there a limit on max number of parallel connections?

**Comment by olegkap** [comment]
Is it the same server or different server and are u trying to do it using the same instance or multiple?

I know some server specify maximum channels per session so what it appears to be happening is that one of the request causes to session to close cause it exceeds number of allowed channels  while on of the parallel uploads still trying to upload or authenticate using closed an d probably disposed session, since we get null exception here already.

Try to limit upload to 10 and see if problem occurs ( I think most server support 10 channels per session) then try with 11.

Thanks,
Oleg

**Comment by a-saqib** [comment]
Hi Oleg,

Thanks for chiming in. I am uploading same file to different servers in parallel, and I am creating separate instance of `ScpClient` for each upload session in its own thread. This problem is completely random and only occurs once (or maybe twice) over 100's of execution, but when it does it makes my app crash which is bad. :)

Appreciate your help.

Adeel

**Comment by drieseng** [comment]
What version of SSH.NET are you using?

**Comment by a-saqib** [comment]
Thanks for the reply. We're using SSH.NET from 2014.

**Comment by drieseng** [comment]
@adeelsaqib Please try the latest version, and let us know if you can still reproduce this issue.

**Comment by a-saqib** [comment]
Hi @drieseng,

Unfortunately, we have hit this issue again with more recent version of SSH.NET, i.e. 2016.0.0.0. Below is the call stack from new instance.

Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Renci.SshNet.KeyboardInteractiveAuthenticationMethod+<>c__DisplayClass14_0.<Session_MessageReceived>b__0()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

Please let me know if you need any other information. Thanks!

Adeel
--
