### ISSUE TITLE
System.Net.Sockets.SocketException (0x80004005): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

### ISSUE THREAD

**Issue by Sandeepsardeck** [sshnet/SSH.NET#1422]
I have got this error randomly. Sometimes it's working and sometimes it gives this error 

Could you tell me what the issue is? I am using the 2020 version.
```

024-05-22 23:40:21,773 [48] ERROR CustomProvider.Import.SFtpFileDownloader - Error occurred in SFTP download
System.Net.Sockets.SocketException (0x80004005): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at Renci.SshNet.Abstractions.SocketAbstraction.Connect(IPEndPoint remoteEndpoint, TimeSpan connectTimeout)
   at Renci.SshNet.Session.SocketConnect(String host, Int32 port)
   at Renci.SshNet.Session.Connect()
   at Renci.SshNet.BaseClient.CreateAndConnectSession()
   at Renci.SshNet.BaseClient.Connect()
   at Intradiem.Svcs.Provider.Hosted.CustomProvider.Import.SFtpFileDownloader.Download(String destinationAbsoluteFileName, Int32 tenantId, String providerInstanceName)
2024-05-22 23:40:21,773 [48] FATAL CustomProvider.Import.FileDownloader - da.xls: Exception occurred on download attempt 1.:A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at Intradiem.Svcs.Provider.Hosted.CustomProvider.Import.FileDownloader.GetDataImportFile(CustomProviderImportFile importFile, Int32 maxDownloadAttempts, Int32 downloadRetryDelay, Int32 tenantId, String providerInstanceName)
   at Intradiem.Svcs.Provider.Hosted.CustomProvider.FileImport.RunImport(String userAssociationName, Int32 tenantId, String providerInstanceName)
   at Intradiem.Svcs.Provider.Hosted.CustomProvider.CustomProviderInterface.ProcessImport(Int32 tenantId, String providerInstanceName)
   at Intradiem.Svcs.Provider.Hosted.CustomProvider.CustomProviderInterface.mIntervalSignal_ProcessQueue(Object source)
   at Knowlagent.Framework.Library.Timers.MinuteIntervalTimerNew.GetMinuteIntervalThread()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by Rob-Hague** [comment]
This is an error from the operating system upon initial connection. There's not much the library can do about that
