### ISSUE TITLE
SshOperationTimeoutException: Session operation has timed out

### ISSUE THREAD

**Issue by rhegner** [sshnet/SSH.NET#222]
When accessing a specific device with _2016.1.0-beta1_ I get the above timeout exception at the end of the session. Here is the call stack:

    Renci.SshNet.Common.SshOperationTimeoutException: Session operation has timed out
       at Renci.SshNet.Session.WaitOnHandle(WaitHandle waitHandle, TimeSpan timeout)
       at Renci.SshNet.Channels.Channel.Close()
       at Renci.SshNet.Channels.ChannelSession.Close()
       at Renci.SshNet.Channels.Channel.Dispose(Boolean disposing)
       at Renci.SshNet.Channels.ChannelSession.Dispose(Boolean disposing)
       at Renci.SshNet.Channels.Channel.Dispose()
       at Renci.SshNet.ShellStream.Dispose(Boolean disposing)
       at System.IO.Stream.Close()
       at System.IO.StreamReader.Dispose(Boolean disposing)
       at System.IO.TextReader.Dispose()
       at <my own code>

**Note 1**
[Here](https://github.com/sshnet/SSH.NET/blob/2016.1.0-beta1/src/Renci.SshNet/Session.cs#L813) it looks like `Session.WaitOnHandle` is not supposed to throw a `SshOperationTimeoutException` when the session is about to disconnect - but it does. So maybe the question boils down to: Why is the `_isDisconnecting` flag not set in this case?

**Note 2**
In `Channel.Close` the `SshConnectionException` is ignored, since we are closing the connection anyway (see [here](https://github.com/sshnet/SSH.NET/blob/2016.1.0-beta1/src/Renci.SshNet/Channels/Channel.cs#L549)). Maybe the `SshOperationTimeoutException` should be ignored there too?

**Comment by petshig** [comment]
Same problem. My program is rebooting machines in loop and i encounter this exception a lot.

**Comment by SimonHeffer** [comment]
I have a similar issue. I set the commandTimeout to 10 seconds and run 'sleep 60' remotely. It correctly times out after 10 seconds but after the exception handling it throws the session exception:

using (var cmd = sshclient.CreateCommand(CommandLine))
{
/ /timeout setup here
try {
cmd.Execute() }
catch ()
{
//log timeout
}
} // seems to get stuck here and eventually throws the session exception

   at Renci.SshNet.Session.Renci.SshNet.ISession.WaitOnHandle(WaitHandle waitHandle)
   at Renci.SshNet.Channels.Channel.Close()
   at Renci.SshNet.Channels.ChannelSession.Close()
   at Renci.SshNet.Channels.Channel.Dispose(Boolean disposing)
   at Renci.SshNet.Channels.ClientChannel.Dispose(Boolean disposing)
   at Renci.SshNet.Channels.ChannelSession.Dispose(Boolean disposing)
   at Renci.SshNet.Channels.Channel.Dispose()
   at Renci.SshNet.SshCommand.UnsubscribeFromEventsAndDisposeChannel(IChannel channel)
   at Renci.SshNet.SshCommand.Dispose(Boolean disposing)
   at Renci.SshNet.SshCommand.Dispose()

**Comment by vinay-singh7954** [comment]
please help us without using 1 min

**Comment by SimonHeffer** [comment]
Sorry Vinay,I don't understand what you want

**Comment by WojciechNagorski** [comment]
SSH.NET has changed a lot. I'm closing the ticket, but if the problem still persists, please feel free to reopen or open a new ticket.
