### ISSUE TITLE
A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

### ISSUE THREAD

**Issue by MinistrBob** [sshnet/SSH.NET#234]
I do:

```
ConnectionInfo ConnNfo = new ConnectionInfo(keyValue.Key, 22, "root", new AuthenticationMethod[]
                    {
                        // Pasword based Authentication
                        new PasswordAuthenticationMethod("root","password"),
                        // Key Based Authentication (using keys in OpenSSH Format)
                        new PrivateKeyAuthenticationMethod("rsa.key"),
                    }
                    );

                    var timeout = new TimeSpan(0,0,60);
                    ConnNfo.Timeout = timeout;

using (var sshclient = new SshClient(ConnNfo))
            {
                tbConsole.AppendText("Connect to " + keyValue.Key + " ...\n");
                sshclient.Connect();
                ExecuteCommand(sshclient, @"hostname", keyValue.Key);
                tbConsole.AppendText("Disconnect from " + keyValue.Key + " ...\n");
                sshclient.Disconnect();
            }
```
			
And I get error on - sshclient.Connect();

```
Connect to 10.128.86.3 ...
ERROR: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
StackTrace:    at Renci.SshNet.Abstractions.SocketAbstraction.Connect(IPEndPoint remoteEndpoint, TimeSpan connectTimeout)
   at Renci.SshNet.Session.SocketConnect(String host, Int32 port)
   at Renci.SshNet.Session.Connect()
   at Renci.SshNet.BaseClient.Connect()
   at SSHBot.Form1.MainTest(KeyValuePair`2 keyValue, ConnectionInfo ConnNfo) in c:\MyGit\SSHBot\SSHBot\Form1.cs:line 253
   at SSHBot.Form1.btStart_Click(Object sender, EventArgs e) in c:\MyGit\SSHBot\SSHBot\Form1.cs:line 98

```   
I try Windows 7 x64 and Windows 2008 R2
FW 4.6.1 and 4.0
In any case I get an error

what am I doing wrong? Or is it a bug?

**Comment by MinistrBob** [comment]
Sorry, i'ts our problem.  It turned out that VPN politicians only allow one session - this was the problem
