### ISSUE TITLE
Dynamic operations can only be performed in homogenous AppDomain

### ISSUE THREAD

**Issue by XceSx6** [sshnet/SSH.NET#252]
At calling Connect on the SFTP Client, i get:
System.InvalidOperationException: Dynamic operations can only be performed in homogenous AppDomain. at Renci.SshNet.Session.WaitOnHandle(WaitHandle waitHandle) at Renci.SshNet.Session.Connect() at Renci.SshNet.BaseClient.Connect()...

Please help.

**Comment by XceSx6** [comment]
at Renci.SshNet.BaseClient.Session_ErrorOccured(System.Object, Renci.SshNet.Common.ExceptionEventArgs)
   at Renci.SshNet.Session.RaiseError(System.Exception)
   at Renci.SshNet.Session.MessageListener()
   at Renci.SshNet.Session.<Connect>b__148_0()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by drieseng** [comment]
As from **2016.1.0-beta1**, we no longer use dynamic dispatching.
Please try using that version or the upcoming **2016.1.0-beta2** release.

**Comment by XceSx6** [comment]
Yup, after Implementing the suggested version the Issue resolved.
Thanks you kindly!
Keep up the good work :)

**Comment by vochitan90** [comment]
Hi guys, I try to use 2016.1.0-beta2 release but still get the same error, please help.

I connect sftp inside timer job of the sharepoint 2013

Thanks!

**Comment by drieseng** [comment]
I only released beta2 moments ago, so I assume you're talking about 2016.1.0-beta1.
Nonetheless, you should not be getting that exception with either version.
