### ISSUE TITLE
.Net Core Issue

### ISSUE THREAD

**Issue by jbarber3388** [sshnet/SSH.NET#268]
I am using version 2016.1.0-beta1 of the SSH.NET library, and I am converting a .Net framework (4.0) console app to a .Net Core (2.0 preview 2) console app. The .Net framework app runs the SSH.NET APIs fine, but when I converted it to .Net Core it now bombs on the creation of the SftpClient object. It looks like it can't fine the specific Cryptography library. Below is the full exception stack trace.

_2017-08-10 10:29:47,718 2406   ERROR [2 ] - Module reported exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeLoadException: Could not load type 'System.Security.Cryptography.HMACRIPEMD160' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at Renci.SshNet.ConnectionInfo..ctor(String host, Int32 port, String username, ProxyTypes proxyType, String proxyHost, Int32 proxyPort, String proxyUsername, String proxyPassword, AuthenticationMethod[] authenticationMethods)
   at Renci.SshNet.PasswordConnectionInfo..ctor(String host, Int32 port, String username, Byte[] password, ProxyTypes proxyType, String proxyHost, Int32 proxyPort, String proxyUsername, String proxyPassword)
   at Renci.SshNet.PasswordConnectionInfo..ctor(String host, Int32 port, String username, String password)
   at Renci.SshNet.SftpClient..ctor(String host, Int32 port, String username, String password)_

The documentation indicates that 2016.1.0-beta1 supports .Net Standard 1.3. So, theoretically this should be compatible .Net core. 

**_Is there possibly something that I am missing to install, or is this a .Net Core vs .Net Standard issue?_**

**Comment by drieseng** [comment]
You (or **Visual Studio**) appear to be still using the **.NET Framework 4.0** binary of **SSH.NET** instead of the **netstandard1.3** binary.

Please try removing the reference to our **NuGet** package, and adding it back.

**Comment by jbarber3388** [comment]
Oh that sounds very possible. I won't be able to test this until another week or so. but I will be sure to try that.

Thanks you for the response.

**Comment by drieseng** [comment]
@jbarber3388 Any news on this?

**Comment by jbarber3388** [comment]
Sorry, I forgot to get back to you!

It turned out to be a Visual Studio issues. After I reset it, it was able to correctly resolve the nuget package. We still have to do a regression test but this issue is resolved.

Thanks again!
