### ISSUE TITLE
SSH NET on dotnet core 2.1

### ISSUE THREAD

**Issue by salorob** [sshnet/SSH.NET#297]
Hi!

Having this code to connect: 

```
 private void Run()
        {
            _Running = true;
            int _Tries = 0;

            while (_Running)
            {
                try
                {
                    _Tries++;
                    _Log.Info($"{_Tries} Creating Client");
                    using (var client = new SshClient(this.Server, 24, this.User, this.Password))
                    {
                        _Log.Info($"{_Tries} Connecting");
                        client.Connect();

                        while (!client.IsConnected && _Running)
                            Thread.Sleep(10);

                        _Log.Info($"{_Tries} Connected");
                        foreach (var entry in Ports)
                        {
                            var apiPort = new ForwardedPortRemote(entry.Key, this.LocalIp, entry.Value);
                            _Log.Info($"{_Tries} Add port");
                            client.AddForwardedPort(apiPort);

                            _Log.InfoFormat("Connecting reverse ssh {0} : {1} @ {2}]", this.LocalIp, entry.Key, entry.Value);
                            apiPort.Start();
                        }

                        _Log.InfoFormat("Connected with {0}", this.Server);

                        _Tries = 0;
                        while (_Running)
                            Thread.Sleep(10);

                        _Log.InfoFormat("Disconnecting from {0}", this.Server);

                        client.Disconnect();
                        client.Dispose();
                    }
                }
                catch (Exception ex)
                {
                    _Log.Error(ex);
                    Thread.Sleep(_Tries > 10 ? 60000 : 10000);
                }
            }
        }
```

This works as expected on dotnetcore when running it on VisualStudio 2017, however; after publishing for linux-arm, and running it on a raspberry pi, i get these errors:

```
13.09.17 19:04:42 (+0200)       
13.09.17 19:05:42 (+0200) info: SSHConnection[0]
13.09.17 19:05:42 (+0200)       109 Creating Client
13.09.17 19:05:42 (+0200) info: SSHConnection[0]
13.09.17 19:05:42 (+0200)       109 Connecting
13.09.17 19:05:47 (+0200) info: SSHConnection[0]
13.09.17 19:05:47 (+0200)       109 Connected
13.09.17 19:05:47 (+0200) fail: SSHConnection[0]
13.09.17 19:05:47 (+0200)       System.AggregateException: One or more errors occurred. (No such device or address) ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: No such device or address
13.09.17 19:05:47 (+0200)          at System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6)
13.09.17 19:05:47 (+0200)          at System.Net.Dns.ResolveCallback(Object context)
13.09.17 19:05:47 (+0200)       --- End of stack trace from previous location where exception was thrown ---
13.09.17 19:05:47 (+0200)          at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
13.09.17 19:05:47 (+0200)          at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
13.09.17 19:05:47 (+0200)          at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
13.09.17 19:05:47 (+0200)          at System.Net.Dns.<>c.<GetHostAddressesAsync>b__25_1(IAsyncResult asyncResult)
13.09.17 19:05:47 (+0200)          at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
13.09.17 19:05:47 (+0200)          --- End of inner exception stack trace ---
13.09.17 19:05:47 (+0200)          at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
13.09.17 19:05:47 (+0200)          at ROPE.Connexxt.Server.SSHConnection.Run()
13.09.17 19:05:47 (+0200)       ---> (Inner Exception #0) System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (0x00000005): No such device or address
13.09.17 19:05:47 (+0200)          at System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6)
13.09.17 19:05:47 (+0200)          at System.Net.Dns.ResolveCallback(Object context)
13.09.17 19:05:47 (+0200)       --- End of stack trace from previous location where exception was thrown ---
13.09.17 19:05:47 (+0200)          at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
13.09.17 19:05:47 (+0200)          at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
13.09.17 19:05:47 (+0200)          at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
13.09.17 19:05:47 (+0200)          at System.Net.Dns.<>c.<GetHostAddressesAsync>b__25_1(IAsyncResult asyncResult)
13.09.17 19:05:47 (+0200)          at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)<---
```

Any clue ?

**Comment by drieseng** [comment]
Can you create a small console app, and check if `Dns.GetHostAddressesAsync("")` works on a RPI?

Pretty sure it's the **ForwardedPortRemote** constructor that is throwing this exception.
What is the value of `this.LocalIp`?

**Comment by drieseng** [comment]
This appears to be an issue with .NET Core:
https://github.com/dotnet/corefx/pull/23794
