### ISSUE TITLE
Information provided by remote host is not captured when channel session is rejected

### ISSUE THREAD

**Issue by gordonwatts** [sshnet/SSH.NET#305]
I've got an intermittent crash I'd like to track down a bit better:

    Unhandled Exception: Renci.SshNet.Common.SshException: Failed to open a channel after 10 attempts.
       at Renci.SshNet.Channels.ChannelSession.Open()
       at Renci.SshNet.ScpClient.Download(String filename, FileInfo fileInfo)
       at AtlasSSH.SSHConnection.CopyRemoteFileLocally(String lx, FileInfo localFile, Action`1 statusUpdate, Func`1 failNow)
       at AtlasWorkFlows.Locations.PlaceLinuxRemote.CopyFromRemoteToLocal(String dsName, String[] files, DirectoryInfo ourpath, Action`1 statusUpdate, Func`1 failNow)
       at AtlasWorkFlows.Locations.PlaceLocalWindowsDisk.CopyFromSCPTarget(IPlace origin, Uri[] uris, Action`1 statusUpdate, Func`1 failNow)

I can see the spot where this error occurs in the source code. But the reasons for the error or failure to open seem to fail. This failure occurs after 15 or 20 connections are opened (and I think closed) to the same machine. And it doesn't always happen.

How can I better track down what is causing this failure?

**Comment by drieseng** [comment]
Right now, we do not capture the information that a remote host provides when it rejects opening a channel session.

We should capture that information, and include it in the exception we raise after `ConnectionInfo.RetryAttempts` failed attempts.

**Comment by drieseng** [comment]
@gordonwatts Until I fix this at our end, you have two options:
* Consult the log of your SSH server.
* Modify `ChannelSession(OnOpenFailure(uint reasonCode, string description, string language)` in **SSH.NET** to capture and log that info.

**Comment by gordonwatts** [comment]
Thanks!

**Comment by drieseng** [comment]
@gordonwatts Is this blocking you? Have you tried my suggestions above?

**Comment by gordonwatts** [comment]
Thanks, no. I re-run a few times and it gets through. I can modify the source so it captures the code and build a myget nuget package to debug what is going on. So, no worries.
