### ISSUE TITLE
Renci.SshNet.Common.SshOperationTimeoutException

### ISSUE THREAD

**Issue by sewarts** [sshnet/SSH.NET#325]
Getting a timeout when uploading a file (yet file is tiny). How do I debug this?

 at Renci.SshNet.Abstractions.SocketAbstraction.Read(Socket socket, Byte[] buffer, Int32 offset, Int32 size, TimeSpan timeout)
   at Renci.SshNet.Session.SocketReadLine(TimeSpan timeout)
   at Renci.SshNet.Session.Connect()
   at Renci.SshNet.BaseClient.Connect()

**Comment by drieseng** [comment]
Are you sure you're connecting to a SSH server?
You can take the **SSH.NET** source and step into the `Session.Connect()` method.

**Comment by sewarts** [comment]
It's external but yes they have assured me it has SSH v2. Thanks will try that.

**Comment by afatnassi** [comment]
Hello @drieseng, I am having the same issue. 
I cloned  the SSH.NET source and integrated my call and I am getting the same error stack in the first comment when trying to connect. I tried pinging the server using `telnet host 22` and I get a response message SSH-2.0-ActiveTransferSSHD after I type something in the command line.
