### ISSUE TITLE
Renci.SshNet.Common.SshOperationTimeoutException

### ISSUE THREAD

**Issue by afatnassi** [sshnet/SSH.NET#339]
Getting this error when trying to connect:

Renci.SshNet.Abstractions.SocketAbstraction.Read(Socket socket, Byte[] buffer, Int32 offset, Int32 size, TimeSpan timeout)
   at Renci.SshNet.Session.SocketReadLine(TimeSpan timeout)
   at Renci.SshNet.Session.Connect()
   at Renci.SshNet.BaseClient.Connect()

My knowledge about these protocols is limited. It seems that the code is waiting on some sort of a return message and timing out. I tried pinging the server `telnet host 22` and I was able to connect but I only get a return message **SSH-2.0-ActiveTransferSSHD** once I've entered a character on the command line. So maybe the connect method is timing out because it's not getting any return message ?

**Comment by Rob-Hague** [comment]
I expect this to have been fixed in 2023.0.1 (#1274)
