### ISSUE TITLE
OpenSSH Linux Server

### ISSUE THREAD

**Issue by FernJohnson** [sshnet/SSH.NET#386]
Is any specific software required on the server to support using these libraries to access the server? I am using OpenSSH on Ubuntu, is there any reason a client using these libraries would not be able to authenticate to the server?

The client is receiving the following error:

System.ArgumentException: 

host at Renci.SshNet.ConnectionInfo..ctor(String host, Int32 port, String username, ProxyTypes proxyType, String proxyHost, Int32 proxyPort, String proxyUsername, String proxyPassword, AuthenticationMethod[] authenticationMethods)

 at Renci.SshNet.PasswordConnectionInfo..ctor(String host, Int32 port, String username, Byte[] password, ProxyTypes proxyType, String proxyHost, Int32 proxyPort, String proxyUsername, String proxyPassword) 

 at Renci.SshNet.PasswordConnectionInfo..ctor(String host, Int32 port, String username, String password) at DealerSocket.Services.BusinessLogic.Integration.FtpSecureClientProxy.Initialize(String host, String userName, String password, EncryptionAlgorithm encryptionAlgorithm, Int32 port)

Thanks

**Comment by darkoperator** [comment]
Only thing that I have encountered is if the server is using elliptical curve keys that are not yet supported by the library

**Comment by drieseng** [comment]
@darkoperator, these are now supported in the **develop** branch.
@FernJohnson, please try building **SSH.NET** from the **develop** branch.
Reopen this issue if you still encounter the same problem.
