### ISSUE TITLE
Problem with SOCKS5 proxy connection

### ISSUE THREAD

**Issue by EKaviShop** [sshnet/SSH.NET#430]
Dear All,

I'm trying to connect to an SFTP server through SOCKS5 proxy. When I try to connect I get

Renci.SshNet.Common.SshConnectionException
**An established connection was aborted by the server.**
Renci.SshNet.Common.SshConnectionException: An established connection was aborted by the server.
   at Renci.SshNet.Session.SocketRead(Int32 length, Byte[] buffer)
   at Renci.SshNet.Session.SocketReadByte()
   at Renci.SshNet.Session.ConnectSocks5()
   at Renci.SshNet.Session.Connect()
   at Renci.SshNet.BaseClient.Connect() exception. 

I'm importing directly the "Renci.SshNet.dll" as a reference into my project.

Any ideas about what is the problem?

PS: I can able to connect from different zone without proxy.

**Comment by frkwtto** [comment]
This problem is KNOWN bug, and already submitted pull request (#174).
But unfotunatelly, this pull request is NOT merged yet.

Until this bug is fixed, you use following code:

`var port = 10022;   // the ssh port that you want to use.`
`var portBytes = BitConverter.GetBytes(System.Net.IPAddress.HostToNetworkOrder((short)port));`
`var port_for_sshnet = portBytes[0] * 0xFF + portBytes[1];`

Then, you set `port_for_sshnet` into Ssh.Net (instead of 10022).

**Comment by EKaviShop** [comment]
Hi,
Thank you for your response.
I had a try with above code. but still am getting the below error.
I tried the above code with both port (port-22 and proxyport-1080). But no luck.

System.Exception: No connection could be made because the target machine actively refused it ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it
   at Renci.SshNet.Abstractions.SocketAbstraction.Connect(IPEndPoint remoteEndpoint, TimeSpan connectTimeout)
   at Renci.SshNet.Session.SocketConnect(String host, Int32 port)
   at Renci.SshNet.Session.Connect()
   at Renci.SshNet.BaseClient.Connect()

Kindly help me on That.
Thank you !

**Comment by frkwtto** [comment]
I'm sorry I can not help you.

I uploaded my example code. (It worked for me.)

URL: [https://gist.github.com/frkwtto/45033ac6ae93104d9c2f36a2420ee1c9](https://gist.github.com/frkwtto/45033ac6ae93104d9c2f36a2420ee1c9)

I hope this would your help.

**Comment by EKaviShop** [comment]
Hi Team,

Thanks for your response.

I have used the same code what you have given.

Still am getting the same error. IS there any chance to check the error code in the exception?

Renci.SshNet.Common.SshConnectionException was unhandled
  HResult=-2146233088
  Message=An established connection was aborted by the server.
  Source=Renci.SshNet
  StackTrace:
       at Renci.SshNet.Session.SocketRead(Byte[] buffer, Int32 offset, Int32 length)
       at Renci.SshNet.Session.SocketReadByte()
       at Renci.SshNet.Session.ConnectSocks5()
       at Renci.SshNet.Session.Connect()
       at Renci.SshNet.BaseClient.Connect()
       at SMTPSample.Program.ListDirectory(ConnectionInfo connectionInfo) in c:\users\sample\documents\visual studio 2015\Projects\SMTPSample\SMTPSample\Program.cs:line 89
       at SMTPSample.Program.Main(String[] args) in c:\users\sample\documents\visual studio 2015\Projects\SMTPSample\SMTPSample\Program.cs:line 33
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 

Thank you !

**Comment by drieseng** [comment]
This was fixed in [2020.0.0-beta1](https://github.com/sshnet/SSH.NET/releases/tag/2020.0.0-beta1).
