### ISSUE TITLE
Illegal principal name when executing command

### ISSUE THREAD

**Issue by hungarianguy** [sshnet/SSH.NET#500]
When executing hive command via ssh (command line or your API) i get the following exception bellow.  does anyone know what I need to set on the server or during execution so it works.

:~/$ ssh USERNAME@YYY.DOMAIN hive -f /tmp/cmfupload_bb95813b-6755-473e-9369
YYY.DOMAINS's password: 

Logging initialized using configuration in file:/etc/hive/conf.dist/hive-log4j.properties
Exception in thread "main" java.lang.RuntimeException: MetaException(message:Error getting current user: failure to login: javax.security.auth.login.LoginException: java.lang.IllegalArgumentException: Illegal principal name USERNAME@XXX.DOMAIN: org.apache.hadoop.security.authentication.util.KerberosName$NoMatchingRule: No rules applied to USERNAME@XXX.DOMAIN
java.io.IOException: failure to login: javax.security.auth.login.LoginException: java.lang.IllegalArgumentException: Illegal principal name USERNAME@XXX.DOMAIN: org.apache.hadoop.security.authentication.util.KerberosName$NoMatchingRule: No rules applied to USERNAME@XXX.DOMAIN
	at org.apache.hadoop.security.UserGroupInformation.loginUserFromSubject(UserGroupInformation.java:840)
	at org.apache.hadoop.security.UserGroupInformation.getLoginUser(UserGroupInformation.java:776)
	at org.apache.hadoop.security.UserGroupInformation.getCurrentUser(UserGroupInformation.java:649)
	at org.apache.hadoop.hive.ql.metadata.Hive.getMSC(Hive.java:3019)
	at org.apache.hadoop.hive.ql.session.SessionState.start(SessionState.java:503)
	at org.apache.hadoop.hive.cli.CliDriver.run(CliDriver.java:677)
	at org.apache.hadoop.hive.cli.CliDriver.main(CliDriver.java:621)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

**Comment by hungarianguy** [comment]
I had to set KRB5_CONFIG and kinit and how I'm able to run command...
