### ISSUE TITLE
Renci.SshNet Object reference not set to an instance of an object after inactivity

### ISSUE THREAD

**Issue by c5racing** [sshnet/SSH.NET#56]
I am using Renci.SsshNet to pull files from a FTP server and process them. This is the method I'm calling to get my file:

```
private byte[] GetFileFromSFtp(string server, int port, string username, string password, string fileName)
    {
        byte[] file;
        var sftp = new SftpClient(server, port, username, password);
        sftp.Connect();
        var fileRead = sftp.OpenRead(fileName);
        using (var memStream = new MemoryStream())
        {
            fileRead.CopyTo(memStream);
            file = memStream.ToArray();
        }

        sftp.Disconnect();
        return file;
    }
```

This works fine and my application starts processing the file; however, after about 20 seconds, i get a NullReferenceException.

System.Transactions Critical: 0 : http://msdn.microsoft.com/TraceCodes/System/ActivityTracing/2004/07/Reliability/Exception/UnhandledUnhandled exception/LM/W3SVC/1/ROOT/TitanApi-1-131146292255812405

```
<ExceptionType>System.NullReferenceException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType><Message>Object reference not set to an instance of an object.</Message><StackTrace>   at Renci.SshNet.Sftp.SftpSession.SendMessage(SftpMessage sftpMessage)
   at Renci.SshNet.Sftp.SftpSession.SendRequest(SftpRequest request)
   at Renci.SshNet.Sftp.SftpSession.RequestClose(Byte[] handle)
   at Renci.SshNet.Sftp.SftpFileStream.Dispose(Boolean disposing)
   at Renci.SshNet.Sftp.SftpFileStream.Finalize()</StackTrace><ExceptionString>System.NullReferenceException: Object reference not set to an instance of an object.
   at Renci.SshNet.Sftp.SftpSession.SendMessage(SftpMessage sftpMessage)
   at Renci.SshNet.Sftp.SftpSession.SendRequest(SftpRequest request)
   at Renci.SshNet.Sftp.SftpSession.RequestClose(Byte[] handle)
   at Renci.SshNet.Sftp.SftpFileStream.Dispose(Boolean disposing)
   at Renci.SshNet.Sftp.SftpFileStream.Finalize()</ExceptionString></Exception></TraceRecord>
The program '[15268] w3wp.exe' has exited with code 0 (0x0).
```

Any suggestions on what may be causing this or am I not disposing of my code properly?

**Comment by drieseng** [comment]
What version of **SSH.NET** are you using ?
Regardless of the actual version that you use, you will not get the **NullReferenceException** if you properly dispose the **SftpFileStream**:

``` cs
using (var fileRead = sftp.OpenRead(fileName))
using (var memStream = new MemoryStream())
{
    fileRead.CopyTo(memStream);
    file = memStream.ToArray();
}
```
