### ISSUE TITLE
SftpPathNotFoundException doesn't contain the errored path

### ISSUE THREAD

**Issue by Deantwo** [sshnet/SSH.NET#567]
It is weird to debug an error throwing a `Renci.SshNet.Common.SftpPathNotFoundException` exception since it doesn't actually say what the path was.

It should be trivial to add another property to the [SftpPathNotFoundException](https://github.com/sshnet/SSH.NET/blob/7691cb0b55f5e0de8dc2ad48dd824419471ab710/src/Renci.SshNet/Common/SftpPathNotFoundException.cs) class and assign it in the constructor. Preferably the argument shouldn't be optional though.

Exception in my specific case is thrown from here:
```
Renci.SshNet.Common.SftpPathNotFoundException: No such file
     at Renci.SshNet.Sftp.SftpSession.RequestOpenDir(String path, Boolean nullOnError)
     at Renci.SshNet.Sftp.SftpSession.ChangeDirectory(String path)
     at Renci.SshNet.SftpClient.ChangeDirectory(String path)
     at <my code>
```
Finding the bug in my code isn't too hard, just requires me to add some more/better exception handling and logging of my `ChangeDirectory` call.

**Comment by Deantwo** [comment]
Could also add the path to the actual exception `message`.
