### ISSUE TITLE
Specified argument was out of the range of valid values.

### ISSUE THREAD

**Issue by kadje** [sshnet/SSH.NET#59]
Hi guys,

I use latest version of SSH.NET (2016.0.0 beta3). I get the following message when my application tries to disconnect from remote server:

System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: length
   at Renci.SshNet.Session.WaitOnHandle(WaitHandle waitHandle, TimeSpan timeout)
   at Renci.SshNet.Session.Renci.SshNet.ISession.WaitOnHandle(WaitHandle waitHandle)
   at Renci.SshNet.Channels.Channel.WaitOnHandle(WaitHandle waitHandle)
   at Renci.SshNet.Channels.Channel.Close(Boolean wait)
   at Renci.SshNet.Channels.ChannelSession.Close(Boolean wait)
   at Renci.SshNet.Channels.Channel.Close()
   at Renci.SshNet.SubsystemSession.Disconnect()
   at Renci.SshNet.SftpClient.OnDisconnecting()
   at Renci.SshNet.BaseClient.Disconnect()
   at DBAService.Logic.FileTransfer.DbaSftpClient.CloseConnection()    at Renci.SshNet.Session.WaitOnHandle(WaitHandle waitHandle, TimeSpan timeout)
   at Renci.SshNet.Session.Renci.SshNet.ISession.WaitOnHandle(WaitHandle waitHandle)
   at Renci.SshNet.Channels.Channel.WaitOnHandle(WaitHandle waitHandle)
   at Renci.SshNet.Channels.Channel.Close(Boolean wait)
   at Renci.SshNet.Channels.ChannelSession.Close(Boolean wait)
   at Renci.SshNet.Channels.Channel.Close()
   at Renci.SshNet.SubsystemSession.Disconnect()
   at Renci.SshNet.SftpClient.OnDisconnecting()
   at Renci.SshNet.BaseClient.Disconnect()
   at DBAService.Logic.FileTransfer.DbaSftpClient.CloseConnection()

Is it related with issue #58 ?

Alex.

**Comment by drieseng** [comment]
Fixed as part of the hardening introduced for issues #58 and #41.
Confirmed by @kadje.
