### ISSUE TITLE
Exception of type 'System.OutOfMemoryException' was thrown

### ISSUE THREAD

**Issue by kadje** [sshnet/SSH.NET#60]
Hi All,

I've upgraded dll from 2014.4.6 to 2016.0.0 and I get this message when application tries to change directory on remote server. 

System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at Renci.SshNet.SubsystemSession.WaitOnHandle(WaitHandle waitHandle, TimeSpan operationTimeout)
   at Renci.SshNet.Sftp.SftpSession.RequestReadDir(Byte[] handle)
   at Renci.SshNet.SftpClient.InternalListDirectory(String path, Action`1 listCallback)
   at Renci.SshNet.SftpClient.ListDirectory(String path, Action`1 listCallback)
   at DBAService.Logic.FileTransfer.DbaSftpClient.GetCdrAndTrfFiles()
   at DBAService.Logic.FileTransfer.FileTransferSession.FileTransferTask()    at Renci.SshNet.SubsystemSession.WaitOnHandle(WaitHandle waitHandle, TimeSpan operationTimeout)
   at Renci.SshNet.Sftp.SftpSession.RequestReadDir(Byte[] handle)
   at Renci.SshNet.SftpClient.InternalListDirectory(String path, Action`1 listCallback)
   at Renci.SshNet.SftpClient.ListDirectory(String path, Action`1 listCallback)
   at DBAService.Logic.FileTransfer.DbaSftpClient.GetCdrAndTrfFiles()
   at DBAService.Logic.FileTransfer.FileTransferSession.FileTransferTask()

Alex.

**Comment by drieseng** [comment]
Fixed as part of the hardening introduced for issues #58 and #41.
Confirmed by @kadje.
