### ISSUE TITLE
SSHConnectionException thrown when SshCommand.Execute called.

### ISSUE THREAD

**Issue by codex-nz** [sshnet/SSH.NET#647]
Connecting to a Nokia 7750SR running TiMOS-C-15.0.R4 I get immediate connection failure when attempting to execute ssh commands to list existing connections and to turn off pagination. Both of these have been proven to work using a PuTTY interactive shell with the same credentials the app will use.
The strange thing is that authentication occurs without issues. It is only when a command is executed that the connection is aborted immediately.

```C#
private const string SetNoPagination = "environment no more ";
private const string GetAllUsersCommand = "show service id 100 ppp session ";

public async Task<IEnumerable<OnlineUserRecord>> GetOnlineUsers()
{
    try
    {
        using (var privateKeyFile = new PrivateKeyFile(_options.PrivateKeyPath))
        using (var connectionInfo = new PrivateKeyConnectionInfo(_options.Host, _options.Username, privateKeyFile))
        using (_client = new SshClient(connectionInfo))
        {
               _client.HostKeyReceived += OnHostKeyReceived;
               _client.ErrorOccurred += OnConnectionError;
               _client.Connect();

               // either this method....
               var output = _client.RunCommand(SetNoPagination).Result;

               // or this method result in a SshConnectionException being thrown after
               // receiving a ConnectionError event. The event is propagated immediately after
               // the call to run or execute the specified command.
               using (var noPagesCommand = _client.CreateCommand(SetNoPagination))
               {
                   var result = noPagesCommand.Execute();
                   _logger.LogDebug($"Command> {noPagesCommand.CommandText}");
                   _logger.LogDebug($"Return value: {noPagesCommand.ExitStatus}");
               }

              using (var allUsersCommand = _client.CreateCommand(GetAllUsersCommand))
              {
                   var allUsersResult = allUsersCommand.Execute();

                   _logger.LogDebug($"Command> {allUsersCommand.CommandText}");
                   _logger.LogDebug($"Return value: {allUsersCommand.ExitStatus}");
                   if (allUsersCommand.ExitStatus != 0)
                   {  }
              }

              _client.ErrorOccurred -= OnConnectionError;
              _client.HostKeyReceived -= OnHostKeyReceived;
              _client.Disconnect();
          }
    }
    catch (ArgumentNullException nullex)
    {
           _logger.LogError(nullex.Message, nullex);
    }
    catch (ArgumentException ex)
    {
           _logger.LogError(ex.Message, ex);
    }
    catch (SshConnectionException conex)
    {
           _logger.LogError(conex.Message, conex);
    }
    catch (SshException sshex)
    {
           _logger.LogError(sshex.Message, sshex);
    }
    catch (InvalidOperationException iopex)
    {
           _logger.LogError(iopex.Message, iopex);
    }

    return null;
}

private void OnHostKeyReceived(object sender, HostKeyEventArgs e)
{
    _logger.LogInformation($"Received host key from ssh connection: {e.HostKeyName}");
    _logger.LogInformation($"Host key data from ssh connection: {e.HostKey}");
    _logger.LogInformation($"Host key fingerprint from ssh connection: {e.FingerPrint}");
}

private void OnConnectionError(object sender, ExceptionEventArgs e)
{
    _logger.LogInformation($"SSH Connection error: {e.Exception.Message}");
    _logger.LogInformation($"SSH Connection error stack: {e.Exception.StackTrace}");
}
```

The stack trace I receive when the exception is thrown is very little help to me, hoping the below is of use for you to help understand what is going wrong:
```
stack:    at Renci.SshNet.Session.WaitOnHandle(WaitHandle waitHandle, TimeSpan timeout)
   at Renci.SshNet.Session.Renci.SshNet.ISession.WaitOnHandle(WaitHandle waitHandle)
   at Renci.SshNet.Channels.Channel.WaitOnHandle(WaitHandle waitHandle)
   at Renci.SshNet.Channels.ChannelSession.SendExecRequest(String command)
   at Renci.SshNet.SshCommand.BeginExecute(AsyncCallback callback, Object state)
   at Renci.SshNet.SshCommand.Execute()
   at Renci.SshNet.SshClient.RunCommand(String commandText)
   at Vygr.Inf.SSH.Client.SshConnector.GetOnlineUsers()
```

It is worth noting that the interface is not the same as a Linux terminal, but is a Linux based CLI implementation. Not sure if this will have an bearing on this issue.

Have tried searching for help via your documentation which was very little help. The recorded issues had some things I could try but none have yielded any fixes.

**Comment by codex-nz** [comment]
After significant debugging it seems likely that this is an intricacy of the OS I am connecting to and not the fault of the library.
Closing as not an issue.
