### ISSUE TITLE
PasswordAuthenticationMethod stopped working

### ISSUE THREAD

**Issue by Bram-diederik** [sshnet/SSH.NET#658]
my code stopped working from 15 april. 
Im a software tester that can write code. Not a dotnet expert. Can some one help me out? 

im using version 2016.0.0 now trying 2016.1.0
```
 public LinuxRunner(string clientHost, string sshUsername, string sshPassword)
        {
            this.sshPassword = sshPassword;
            ConnNfo = new ConnectionInfo(clientHost, 22, sshUsername,
            new AuthenticationMethod[]{
                // Pasword based Authentication
                new PasswordAuthenticationMethod(sshUsername,sshPassword)
             });
            
        }
```

```
Renci.SshNet.Common.SshAuthenticationException: Permission denied (password).
   at Renci.SshNet.ClientAuthentication.Authenticate(IConnectionInfoInternal connectionInfo, ISession session)
   at Renci.SshNet.ConnectionInfo.Authenticate(ISession session, IServiceFactory serviceFactory)
   at Renci.SshNet.Session.Connect()
   at Renci.SshNet.BaseClient.Connect()
   at StepTester.LinuxRunner.UploadScripts() in C:\projects\testen\stepSystemTest\StepTester\LinuxRunner.cs:line 38
   at StepTester.Program.<>c__DisplayClass0_0.<Main>b__0() in C:\projects\testen\stepSystemTest\StepTester\Program.cs:line 148
```

**Comment by biocoder-frodo** [comment]
Asking the obvious question, have you verified with another SSH client (e.g. Putty) that your password is still actually valid?

**Comment by Bram-diederik** [comment]
Yes i have. I also have made a console writeln with the username and password to be sure the software retrieved the password from a webservice correctly.

**Comment by biocoder-frodo** [comment]
Do the server and client still agree on the used cipher schemes? Please see the SshNet.Logging Verbose messages in your Debug window to see any hints as to why your server hates you. Talk to your sysadmin if there were any changes on the servers you are trying to connect to?

**Comment by Bram-diederik** [comment]
Can i get back to you when there is budget to look in to this?
