### ISSUE TITLE
Client not connected

### ISSUE THREAD

**Issue by The-Futurist** [sshnet/SSH.NET#703]
We get an occasional problem when closing a stream.

**Message=Client not connected. ->    
   at Renci.SshNet.Session.SendMessage(Message message)
   at Renci.SshNet.Session.Renci.SshNet.ISession.SendMessage(Message message)
   at Renci.SshNet.Channels.Channel.SendData(Byte[] data, Int32 offset, Int32 size)
   at Renci.SshNet.Channels.Channel.SendData(Byte[] data)
   at Renci.SshNet.SubsystemSession.SendData(Byte[] data)
   at Renci.SshNet.Sftp.SftpSession.SendRequest(SftpRequest request)
   at Renci.SshNet.Sftp.SftpSession.RequestClose(Byte[] handle)
   at Renci.SshNet.Sftp.SftpFileStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at System.IO.StreamReader.Dispose(Boolean disposing)
   at System.IO.TextReader.Dispose()
   at Renci.SshNet.SftpClient.ReadAllLines(String path, Encoding encoding)
   at Renci.SshNet.SftpClient.ReadLines(String path)**

The apps in question are using SSH.NET 2016.1.0 (net46).

This seems to be the most recent version on the nuget site.

**Comment by BBauer42** [comment]
I also receive this quite frequently.

**Comment by asos-amirthalingamraj** [comment]
I am facing the same issue in the recent version 2024.1.0. Any updates or leads on this?

**Comment by Rayzbam** [comment]
Any update on this ?
