### ISSUE TITLE
Failure while moving file using MoveTo method

### ISSUE THREAD

**Issue by csoumita2000** [sshnet/SSH.NET#756]
Hi,

I am facing an error while copying a file from one folder to another in SFTP share. The error only states "failure". It was working perfectly fine 2 weeks before, now it does not work anymore. 
My code:
                        List<SftpFile> remote_files = new List<SftpFile>();
                        remote_files = sftp.ListDirectory("/data/Ecounsel/").Where(y => y.Name.Contains(".xml")).ToList();
                        foreach (var file in remote_files)
                        {
                            file.MoveTo("/data/appfolder/Archive/" + file.Name + ".processed"); <----Error on this line
                            logger.Info("File " + file.Name + " archived successfully.");
                        }

Stack trace:
                        
                         Failure
                         at Renci.SshNet.Sftp.SftpSession.RequestRename(String oldPath, String newPath)
                         at Renci.SshNet.Sftp.SftpFile.MoveTo(String destFileName)

Could you please help regarding this?

Just a note, I am using the 2020.0.0-beta1 version.

Thanks and Regards,
Soumita

**Comment by csoumita2000** [comment]
Could anyone please help me regarding this issue? Is it because I am using the beta version of SSH.NET?

Version used: 2020.0.0-beta1

**Comment by AsgerBertel** [comment]
Hi, 

I had the exact same issue, and it was caused due to an SFTP issue. 

My SFTP server returns this error, when trying to move the file manually:
General failure (server should provide error description).
Error code: 4
Error message from server: Failure

Common reasons for the Error code 4 are:
- Renaming a file to a name of already existing file.
- Creating a directory that already exists.
- Moving a remote file to a different filesystem (HDD).
- Uploading a file to a full filesystem (HDD).
- Exceeding a user disk quota.

To fix this, remove the existing file from the folder you want to .MoveTo()

**Comment by lbehal** [comment]
I am having this issue as well.
Renci.SshNet.Common.SshException: Can't rename file or directory
   at Renci.SshNet.Sftp.SftpSession.RequestRename(String oldPath, String newPath)
   at Renci.SshNet.Sftp.SftpFile.MoveTo(String destFileName)

I am testing that the destination file is not existing beforehand.
Is it possible that the file is somehow locked?
Because when the code tries to process the same file again it gets to be moved OK.
