### ISSUE TITLE
Data longer than 2147483647 is not supported.

### ISSUE THREAD

**Issue by dinehs** [sshnet/SSH.NET#757]
System.NotSupportedException: Data longer than 2147483647 is not supported.
   at Renci.SshNet.Session.WaitOnHandle(WaitHandle waitHandle, TimeSpan timeout)
   at Renci.SshNet.Session.Connect()
   at Renci.SshNet.BaseClient.Connect()

**Comment by IgorMilavec** [comment]
The limitation of int.MaxValue bytes is due to dotnet's maximum array length. However, based on the call stack I assume the issue is protocol violation on the server's side.
