### ISSUE TITLE
Exception in 2020.0.0. But works in 2020.0.0-beta1.

### ISSUE THREAD

**Issue by frankhommers** [sshnet/SSH.NET#771]
I now get this SshConnectionException: 
```
The server response contains a null character at position 0x00000028:

  00000000  53 53 48 2D 32 2E 30 2D 4F 70 65 6E 53 53 48 5F  SSH-2.0-OpenSSH_
  00000010  37 2E 34 70 31 20 44 65 62 69 61 6E 2D 31 30 2B  7.4p1 Debian-10+
  00000020  64 65 62 39 75 37 0A 00                          deb9u7..

A server must not send a null character before the Protocol Version Exchange is complete.

More information is available here:
https://tools.ietf.org/html/rfc4253#section-4.2
```

at 

```
   at Renci.SshNet.Connection.ProtocolVersionExchange.SocketReadLine(Socket socket, TimeSpan timeout, List`1 buffer)
   at Renci.SshNet.Connection.ProtocolVersionExchange.Start(String clientVersion, Socket socket, TimeSpan timeout)
   at Renci.SshNet.Session.Connect()
   at Renci.SshNet.BaseClient.CreateAndConnectSession()
   at Renci.SshNet.BaseClient.Connect()
```

**Comment by frankhommers** [comment]
Already fixed! Brand new package at nuget.org. It's fixed in `2020.0.1`

**Comment by drieseng** [comment]
@frankhommers Speciaal voor jou :p

**Comment by frankhommers** [comment]
> @frankhommers Speciaal voor jou :p

Wat een liefde ;-)
