### ISSUE TITLE
Command Execution - The requested length (4) is greater than the actual number of bytes read (0)

### ISSUE THREAD

**Issue by chickentech** [sshnet/SSH.NET#820]
I'm trying to execute commands to a Cradlepoint device.  Connection establishes fine, but when I execute any command I get the following:

```
System.ArgumentOutOfRangeException: 'The requested length (4) is greater than the actual number of bytes read (0).
Parameter name: length'
```

I can putty in just fine and execute these commands.  I don't see anything very special.  Only issue I can find that might be related is closed already:  [Ignore data of SSH_MSG_IGNORE when its specified length is greater than the actual available bytes](https://github.com/sshnet/SSH.NET/issues/41)

I am on the latest 2020.0.1 release as well.  Any help would be greatly appreciated!

**Comment by chickentech** [comment]
Just saw the info you'd like to see in issues, so here it is:

Remote Server Information
Remote SSH Server version: **SSH-2.0-CradlepointSSHService**
Remote Operating System distribution name and architecture (x32/x64): **Cradlepoint NCOS - to my knowledge, x32 Linux-based**
What kind of access do you have?: **admin privileges**
Does Putty/WinSCP work?:  **Yes**

Local Machine Information
Operating System (for Windows, run winver.exe): **Windows 10 20H2**
.NET Framework versions installed (See C:\WINDOWS\Microsoft.Net\Framework): **v1.0.3705, v1.1.4322, v2.0.50727, v3.0, v3.5, v4.0.30319**

Project information
What is your target framework and architecture (x32/x64)?:  **x32**
Is your project multi-threaded/complex?: **No**

Source Code
**Sample Code:**
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Renci.SshNet;

namespace CPRenciTest
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var client = new SshClient("REMOVED", "REMOVED", "REMOVED"))
            {
                client.Connect();
                var output = client.RunCommand("vpn");
                Console.WriteLine(output);
                client.Disconnect();
            }
            Console.ReadKey();
        }
    }
}
```
**Exceptions and Stack Trace/Call Stack:**
```
System.ArgumentOutOfRangeException: 'The requested length (4) is greater than the actual number of bytes read (0).
Parameter name: length'
```
```
   at Renci.SshNet.SshCommand.WaitOnHandle(WaitHandle waitHandle)
   at Renci.SshNet.SshCommand.EndExecute(IAsyncResult asyncResult)
   at Renci.SshNet.SshClient.RunCommand(String commandText)
   at CPRenciTest.Program.Main(String[] args) in C:\Users\nat\source\repos\CPRenciTest\CPRenciTest\Program.cs:line 17
```

**Comment by chickentech** [comment]
Return encoding is causing this problem.  Caught the exception and ignored it and was able to continue on.  I'm going to close this, but if anyone else later sees this issue, just catch and ignore the exception.
