### ISSUE TITLE
Exception Renci.SshNet.Common.SshException: 'Channel was closed'  while executing any operation

### ISSUE THREAD

**Issue by S-Jindal** [sshnet/SSH.NET#847]
I am running this on `Target framework = .NET Core 3.1.410`

```
message='Http request failed with unexpected exception of type 'SshException' and message exception: 'Channel was closed.'.', exception='Renci.SshNet.Common.SshException: Channel was closed.
[2021-07-08T11:06:17.809Z]    at Renci.SshNet.SubsystemSession.WaitOnHandle(WaitHandle waitHandle, Int32 millisecondsTimeout)
[2021-07-08T11:06:17.810Z]    at Renci.SshNet.Sftp.SftpSession.RequestRealPath(String path, Boolean nullOnError)
[2021-07-08T11:06:17.810Z]    at Renci.SshNet.Sftp.SftpSession.GetCanonicalPath(String path)
[2021-07-08T11:06:17.811Z]    at Renci.SshNet.SftpClient.InternalListDirectory(String path, Action`1 listCallback)        
[2021-07-08T11:06:17.812Z]    at Renci.SshNet.SftpClient.ListDirectory(String path, Action`1 listCallback)
```

Please note that `sftpClient.Connect()` call was successful.
All the SFTP operations are throwing this exception even though I can see the logs on the server which says **Session connected**.

Is it not supported on Core 3.1?

This is my code snippet:
```
var connectionInfo = new PasswordConnectionInfo(host: host, username: username, port: port, password: password)
                {
                    ChannelCloseTimeout = TimeSpan.FromSeconds(20),
                };

                using (var serviceClient = new SftpClient(connectionInfo: connectionInfo))
                {
                    serviceClient.OperationTimeout = new TimeSpan(hours: 0, minutes: 1, seconds: 10);
                    serviceClient.KeepAliveInterval = TimeSpan.FromMinutes(1);
                    serviceClient.Connect();
                    var root = ServiceOperationsProviderUtilities.GetParameterValue("rootDirectory", connectionParameters).ToString();
                    root = root + "/Movies";
                    var result = serviceClient.ListDirectory(root);
                }
```

Any pointers?

**Comment by S-Jindal** [comment]
There was most likely an issue with the SFTP server, when I switched server things started working. 
Closing this.
