### ISSUE TITLE
DownloadFile read exception 

### ISSUE THREAD

**Issue by imapangolin** [sshnet/SSH.NET#868]
I’m getting exception.  Can anyone advise how to diagnose this or what could be going wrong? 

Renci.SshNet.Common.SshException: Channel was closed.
   at Renci.SshNet.Sftp.SftpFileReader.Read()
   at Renci.SshNet.SftpClient.InternalDownloadFile(String path, Stream output, SftpDownloadAsyncResult asyncResult, Action`1 downloadCallback)
   at Renci.SshNet.SftpClient.DownloadFile(String path, Stream output, Action`1 downloadCallback)
   at ftpSimple.FP.GetFileSFTP(String ClientFileName, String ServerFileName, String ServerName, String Port, String UserID, String Password)

**Comment by IgorMilavec** [comment]
Duplicate of #880
