### ISSUE TITLE
Mac error on DownloadFile 

### ISSUE THREAD

**Issue by seultwo** [sshnet/SSH.NET#874]
I'm experiencing a MAC Error when i use client.DownloadFile() and when the file size is greater that the buffer size. If the file size is lower, there's no issue.  Upload works perfectly with same settings.

My connection Info:

![image](https://user-images.githubusercontent.com/1569332/134026639-2650c1e7-13e0-4063-8e2e-efc981311a4d.png)

**Comment by jacksonAspect** [comment]
I am also having this exact issue. For me, it happens in a UWP project. It's works perfectly in a WPF project though.

**Comment by jacksonAspect** [comment]
I got around it by creating a full trust service to perform the SFTP download through .NET Framework with this guide and some modifications: [https://techcommunity.microsoft.com/t5/windows-dev-appconsult/get-a-list-of-virtual-serial-com-ports-from-uwp-app/ba-p/723207](url)

**Comment by patch91484** [comment]
I have this problem as well. Also working fine in a WPF project, problem only occurs in a UWP project:

Renci.SshNet.Common.SshConnectionException
  HResult=0x80131500
  Message=MAC error
  Source=Renci.SshNet
  StackTrace:
   at Renci.SshNet.SshCommand.WaitOnHandle(WaitHandle waitHandle)
   at Renci.SshNet.SshCommand.EndExecute(IAsyncResult asyncResult)
   at Renci.SshNet.SshClient.RunCommand(String commandText)
   at mGuard_Config_UWP.OpenVPN_Config.<reqcert_Click>d__7.MoveNext() in C:\Users\pats\source\repos\mGuard Config UWP\mGuard Config UWP\OpenVPN Config.xaml.cs:line 123

**Comment by patch91484** [comment]
It appears using the Neon.SSH.NET version works with UWP.

**Comment by Marcel-Soratus** [comment]
@jacksonAspect Can you please share your code how you managed the full trust service? I'm having troubles implementing with that.

**Comment by Wufus** [comment]
Bug still exist in `SSH.NET 2020.0.2` for UWP

**Comment by Wufus** [comment]
Also cant read any bytes from big file using `OpenRead`
