### ISSUE TITLE
How to authenticate with id_rsa.ppk file?

### ISSUE THREAD

**Issue by makrushin-evgenii** [sshnet/SSH.NET#900]
Hi. Sorry for dummy question

Couldn't figure out how to use PrivateKeyAuthenticationMethod. I have two files:

`/id_rsa.ppk`
```
PuTTY-User-Key-File-2: ssh-rsa
Encryption: none
Comment: rsa-key-20210616
Public-Lines: 6
***
Private-Lines: 14
***
Private-MAC: ***
```

`/id_rsa.pub`
```
---- BEGIN SSH2 PUBLIC KEY ----
Comment: "rsa-key-20210616"
***
---- END SSH2 PUBLIC KEY ----
```

In FileZilla, the connection is configured this way and works fine:
![image](https://user-images.githubusercontent.com/14077902/142185314-35a41bf0-e920-408c-9537-3d7f7dd3681b.png)

How to configure the same connection with Renci.SshNet? This code throws exception:
```csharp
var connectionInfo = new ConnectionInfo(
	"host",
	"username",
	new PrivateKeyAuthenticationMethod("username", new[]
	{
		new PrivateKeyFile(@"C:\Users\e.makrushin\Downloads\nielsen_ssh\id_rsa.ppk"),
	})
);
using var client = new SftpClient(connectionInfo);
client.Connect();

Unhandled exception. Renci.SshNet.Common.SshException: Invalid private key file.
   at Renci.SshNet.PrivateKeyFile.Open(Stream privateKey, String passPhrase)
   at Renci.SshNet.PrivateKeyFile..ctor(String fileName, String passPhrase)
   at Renci.SshNet.PrivateKeyFile..ctor(String fileName)
   at ConsoleApp1.Program.Main(String[] args) in C:\Users\e.makrushin\RiderProjects\Draft\ConsoleApp1\ConsoleApp1\Program.cs:line 12
```

**Comment by durranitech** [comment]
ppk is putty format. Use puttygen to convert to openssh format

**Comment by IgorMilavec** [comment]
@makrushin-evgenii was the question answered? If yes, please close the issue.
